server:
  port: 7077
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: satyasairedyy261@gmail.com
    password: satyasai@96
    properties:
       mail:
         smtp:
          auth: true
          starttls:
           enable: true

